### ISSUE TITLE
Importing accounts causing crashes. 

### ISSUE THREAD

**Issue by auAuth** [rex706/SAM#160]
On the release version v1.5.0.1 When importing my config from previous versions, my SAM was crashing and I had to import everything over manually. Now after downloading the update, my SAM will crash right after it is opened unless I delete the config files located in the folder it is in will again have to manually re-add the accounts. 

https://user-images.githubusercontent.com/115546346/207473519-9d3a9d5c-c4f6-4539-81f0-f4bcae136044.mp4

**Comment by auAuth** [comment]
@rex706 yes I had been building from source on a couple occasions, I think I had last done so about 3 days before you pushed the release

**Comment by rex706** [comment]
@auAuth this happens because the public release has a different private key value used for the sensitive account info, which makes the data files incompatible between local builds and releases. I will look into making a specific error message so the program doesn't just crash with no other information.
