### ISSUE TITLE
Suggestion: Make usage og auto launch account during windows startup

### ISSUE THREAD

**Issue by wazerstar** [rex706/SAM#20]
Lets say you can make program startup during windows startup and be able to select one account that can startup after a period of 5 seconds if not interrupted, this way we can make sure that steam is always logged into desired account during reboot

**Comment by wazerstar** [comment]
I just found out its implemented, but its bugging, it will crash randomly if you click pre selected, then you are forced to clean the ini file and start all over.

**Comment by rex706** [comment]
I'm not quite sure how you're crashing. I just tried going through it a few times and nothing bad happened for me.

Are you selecting 'Auto Login' on the account you want to be shown as 'Pre-selected'?

If I don't have an account selected for 'Auto Login', trying to select 'Pre-selected' shouldn't do anything unless you had something already set for this previously.

**Comment by wazerstar** [comment]
> 
> 
> I'm not quite sure how you're crashing. I just tried going through it a few times and nothing bad happened for me.
> 
> Are you selecting 'Auto Login' on the account you want to be shown as 'Pre-selected'?
> 
> If I don't have an account selected for 'Auto Login', trying to select 'Pre-selected' shouldn't do anything unless you had something already set for this previously.
> 
> Edit: do you mean it crashes during the windows start up process?

There's a lot of bugs, i will paste most common I have when I test the app.


Having a another window infront and using auto minimize will cause the auth window not to show and give wrong error message.

Perhaps make pause and ask user to make auth window infront.

http://prntscr.com/mp9jod

-------------------------------------------------------------------------

Having these settings where I select settings in the gui it instantly crash, and you can no longer start the app it instantly crashes all the time.


[System]
Version=1.2.3.2
[Settings]
AccountsPerRow=5
StartWithWindows=False
StartMinimized=False
Steam=
[AutoLog]
Recent=True
RecentAcc=
Selected=False
SelectedAcc=

--------------------------------------------------------------------------

Having these settings where I selected "pre select" in settings, it instantly crashed , without having steam open, maybe check if steam is open before and or ask if user wants to start steam?

Also the crash seems to be because I did not set Steam= path.


[System]
Version=1.2.3.2
[Settings]
AccountsPerRow=5
StartWithWindows=False
StartMinimized=False
Steam=
[AutoLog]
Recent=True
RecentAcc=
Selected=False
SelectedAcc=


In both scenarios i'm forced to delete ini file.

**Comment by wazerstar** [comment]
oh and for first initial run, perhaps read Computer\HKEY_CURRENT_USER\Software\Valve\Steam 
string
REG_EZ
SourceModInstallPath it will read example **D:\Games\Steam\steamapps\sourcemods**

remove from string \steamapps\sourcemods and you have steam path.

Then you can ask users on initial run that "We found this steam path, is this correct" yes / no :)?

**Comment by rex706** [comment]
That's actually a really good idea. I had not thought about checking the reg keys for that info.

**Comment by wazerstar** [comment]
btw. you could eliminate the users to point to profile url simply by reading

Steam\config\config.vdf file then match up the username they add in SAM with the one found in config.vdf and then simply extract the steam id 


http://prntscr.com/mp9tx4

and parse to


http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=APIKey&steamids=76561197960435530

Which will give you those details.
http://prntscr.com/mp9uwe

**Comment by rex706** [comment]
I discovered that you can get this info without having to parse the config.vdf by utilizing:

https://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/?key=ApiKey&vanityurl=userName

from the web api as well and then use the GetPlayerSummaries api call after. This way it should work every time regardless of whether or not the local steam files have knowledge of the account and as long as the account name was entered correctly.

However, I'm not sure how this will affect users that have to use their email address, instead of their username, to log in.

**Comment by wazerstar** [comment]
My account is from day 1, I use email, I could test.

**Comment by rex706** [comment]
@wazerstar Does your config.vdf have your email address listed for that user's name?

**Comment by wazerstar** [comment]
> 
> 
> @wazerstar Does your config.vdf have your email address listed for that user's 'Account'?

Yes

```
"Accounts"
				{
					"name@mail.dk"
					{
						"SteamID"		"765611xxxxxxxxxxxxxxx"
```

**Comment by rex706** [comment]
@wazerstar Perfect, it should work fine then. I will change the priority to parse the config.vdf first and then check the web api if that fails instead of the other way around. 

I should be able to make a new release this week if not later today if all goes well!

**Comment by wazerstar** [comment]
> 
> 
> @wazerstar Perfect, it should work fine then. I will change the priority to parse the config.vdf first and then check the web api if that fails instead of the other way around.
> 
> I should be able to make a new release this week if not later today if all goes well!

Will you make checks for active window or maybe do better method like using [controlsend](https://www.autoitscript.com/autoit3/docs/functions/ControlSend.htm) that autoit uses, I guess whatever language you use it should be possible too?

**Comment by rex706** [comment]
@wazerstar  So I actually do check for that actively now. There is a function called .WaitForInputIdle(), which I use to wait for the Steam process to expect input, but for some reason doesn't want to work every single time. I tried to fix this by forcing it to manually wait for a second and then make sure the 2FA window is at the front for every single key press instead of just at the beginning of entering the code, which seems to work much better for me.  

SAM actually does the version checking, and not Updater.exe. The first thing that SAM does when opened is look for a new version, and if one exists, utilizes the Updater.exe to download and install the new version. If you try to run the Updater.exe by itself, it will just go ahead and download the latest version as if it was out of date. The current version of the Updater.exe that is bundled with SAM is super out of date and has the URL's used for updating hard coded, which is obviously not a very good idea. I have a newer version of the Updater that I am getting ready to bundle with this next SAM release as well to address this problem and then move all permalinks into GitHub for consistency. If you want to make sure that your SAM is in fact up to date, clicking 'Help' from the file menu will display the current version or that an update is available. You should be prompted when opening SAM if there is an update available, though.

**Comment by rex706** [comment]
@wazerstar There may still be some discrepancies with waiting for the 2FA window, but try the new version and let me know what you think.

**Comment by wazerstar** [comment]
@rex706 I only tested 3 accounts and all 3 accounts failed with image profile, 2 of them getting profile pictures from alias steam accounts that actually is the login for my accounts and my main I just deleted the profile in sam to test if it would grab the image it self, nothing happen.

**Comment by rex706** [comment]
@wazerstar The 4 accounts I was testing with all worked fine for me and they all are different. Some don't have an alias url, for example. While I can't test the email account, it should work the exact same way. 

SAM now checks the config.vdf _first_ for any accounts that match what is entered in the Username field. It will then use the SteamId attached like in your original suggestion to find your profile image. If that doesn't exist in the config file, it will then try to use the Web Api to obtain the SteamId. 

If some of your accounts have identical aliases, do you have any suggestion to how SAM should be able to know this if they don't exist as separate entries in the config file?

**Comment by wazerstar** [comment]
You cannot have identical aliases, thats why i mentioned you should use the web api to pull their profile steamid steam installation it self first via the config.vdf then compare the steam id via this link
and get their logo that way.

`api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=XXXXXXXXXXXXXXXXX&steamids=76561197960435530`
`
api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=XXXXXXXXXXXXXXXXX&steamids=STEAMID`

**Comment by rex706** [comment]
@wazerstar Here is the C# function that SAM currently uses in the new update to get the user JSON:
https://github.com/rex706/SAM/blob/abbffda2fd4b7f83bbc1e4941156dba3e89e0a6e/SAM/Utils.cs#L202

As you can see, it first tries to find the SteamId from the config.vdf, and only if that fails, try to get the SteamId from `"http://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/?key=" + apiKey + "&vanityurl=" + userName`.

If a valid steam Id is found by the end of these checks, it then calls GetUserInfoFromWebApiBySteamId(steamId), which uses `"https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=" + apiKey + "&steamids=" + steamId` to get the user JSON.

I'm struggling to figuring out how this does not work for you, but it does for me on all 4 accounts from a fresh info.dat file since they appear in my config file.

**Comment by wazerstar** [comment]
I will test again with totally clean SAM extract and add multiple accounts and see if it works.

**Comment by rex706** [comment]
Alright I will do some more testing myself and potentially create a log file to better sort this stuff out. I should be able to spoof a couple email accounts with my own steamids to better test that scenario as well.

Are the 4 accounts that failed all email users? Very weird they are not being recognized by the Vdf parser. 

Thanks for your patience with these issues!

**Comment by wazerstar** [comment]
> 
> 
> Alright I will do some more testing myself and potentially create a log file to better sort this stuff out. I should be able to spoof a couple email accounts with my own steamids to better test that scenario as well.
> 
> Are the 4 accounts that failed all email users? Very weird they are not being recognized by the Vdf parser.
> 
> Thanks for your patience with these issues!

both :)

**Comment by rex706** [comment]
@wazerstar is it possible that the case of the account names are the issue? In the current release, if what is in the username field does not exactly match the case of what appears in the config.vdf, it won't work. I could make everything lowercase in the code to prevent this problem if this is the case.

**Comment by wazerstar** [comment]
I can give you an account that takes picture from another account

This is the login name zuler all lower and profile is https://steamcommunity.com/id/the12341/ 

but takes picture from https://steamcommunity.com/id/Zuler/

**Comment by rex706** [comment]
@wazerstar very strange. It works for me if I add that info to my config file. What is the file path to your config.vdf? The path I use in the code is:

https://github.com/rex706/SAM/blob/08c337f826adacfd882565208bab56819b058618/SAM/Utils.cs#L212

and my steamPath = `c:/program files (x86)/steam/`, which was found from my registry key.

**Comment by wazerstar** [comment]
> 
> 
> @wazerstar very strange. It works for me if I add that info to my config file. What is the file path to your config.vdf? The path I use in the code is:
> 
> [SAM/SAM/Utils.cs](https://github.com/rex706/SAM/blob/08c337f826adacfd882565208bab56819b058618/SAM/Utils.cs#L212)
> 
> Line 212 in [08c337f](/rex706/SAM/commit/08c337f826adacfd882565208bab56819b058618)
>  dynamic config = VdfConvert.Deserialize(File.ReadAllText(steamPath + "config\\config.vdf")); 
> 
> and my steamPath = `c:/program files (x86)/steam/`, which was found from my registry key.

D:\Games\Steam\config

could we do some skype/discord/steam chat instead of this :D

**Comment by rex706** [comment]
@wazerstar add me on discord: rex706#6521

**Comment by wazerstar** [comment]
done

**Comment by rex706** [comment]
Turns out that my config.vdf was very out of date and used a lowercase "steam" in the property path to "Accounts" instead of an uppercase "Steam", and therefore parsing the config for most people fails. I fixed this for the next release, but for now you can manually change your config.vdf "Steam" property to lowercase to get the parsing to work correctly. I have not noticed any side effects of doing this as it has been this way for me for months at the very least.

I also figured out that the call to SetForegroundWindow(); on the Steam Guard Window handle does not work, and I actually have to use the Steam Login window handle for this. Since "Steam Login" is not always in English, I am going to look for where the title text contains "Steam" and does not contain "-". Since the Steam process should have been closed before this is happening, I shouldn't have to worry about it getting confused with the actual Steam window. 

I will try to have a new release out with fixes as soon as I can :)
