### ISSUE TITLE
Sam to steam-partable

### ISSUE THREAD

**Issue by gipperpank** [rex706/SAM#21]
please add a condition to: if " SAM "in the same deriktorii" Steam.exe "then do not display the search dialog" Steam.exe " is for portable versions of Steam

if you do not specify the location "Steam.exe " but " SAM "will be in the same directory that everything works but interferes with the search dialog" Steam.exe"

**Comment by rex706** [comment]
The next release of SAM will search for the installed Steam path via the registry, but I will also include checking the directory it is installed in, as it may not make a registry entry in portable mode.

**Comment by gipperpank** [comment]
one of the features of "Steam portable vers."that it at start it adds keys to the register and at correct completion deletes them (saving locally) and if "Steam" is on USB, then on the following computer "SAM" will request a place position "Steam.exe "I would like to unite" SAM " and "Steam" in the portable version that at start the first was started "SAM" and it in turn started "Steam" and that everything could be updated and worked with " USB "

**Comment by rex706** [comment]
Thanks for the additional explanation. I will also have SAM check if the saved Steam path exists on launch, and if not, trigger the auto-lookup (including your initial suggestion to check the SAM install directory), which if that fails will prompt for the user to locate Steam since the registry key is removed when it closes in portable mode as you said.
