### ISSUE TITLE
improper use of steam api

### ISSUE THREAD

**Issue by a6d6061ed1** [rex706/SAM#27]
I may be mistaken but...

right here: https://github.com/rex706/SAM/blob/262d8240bb41a6bdd48ea845a241d547b7dd4452/SAM/TextDialog.xaml.cs#L78
is an attempt to resolve steamid using steam login (username). This has no chance to ever work because "ResolveVanityURL" webapi method takes **vanityurl** as parameter which is steam custom URL and not steam login username.

I checked to make sure and if I try to resolve steamid using my steam login, it doesn't return any matches.

**Comment by rex706** [comment]
@a6d6061ed1 you are correct and unfortunately this does not work well in many cases. I think this will actually only work correctly if you set your profile url on your account in steam to your username.

For example, my account community url is `https://steamcommunity.com/id/rex706` so it would work for me on that particular account if it did not already exist in the config.vdf. 

As far as I know, there is not an api call that will resolve the SteamId from the account name instead of the vanityUrl. I may get rid of this entirely as another user was experiencing problems with it resolving the wrong information.

[Here](https://developer.valvesoftware.com/wiki/Steam_Web_API) is the web api documentation, and pretty much everything player related requires the SteamId as a parameter.

**Comment by rex706** [comment]
@a6d6061ed1 The latest release should address the issue with parsing the config file incorrectly, so give it another try and let me know if it works better for resolving your account info.
