### ISSUE TITLE
Account Generator

### ISSUE THREAD

**Issue by marius137** [rex706/SAM#32]
Is it possible to integrate an account generator in the manager? maybe a dropdown menu with Extras>Generate account

If you don't want to make the generator yourself, you can maybe integrate the API of [https://accgen.cathook.club/](url)

**Comment by rex706** [comment]
Interesting suggestion 🤔

**Comment by rex706** [comment]
I requested an API key for the service you provided, and they reached out letting me know that the only way this could work without everyone abusing the single key they gave me, since it's limited to a certain amount of accounts per day and per hour, is to allow users to request a key themselves and have an input field it. Since I have no idea what it would take to create a generator myself, I think this is the best plan for now. I should be able to have this ready for the next release.

**Comment by a6d6061ed1** [comment]
I wouldn't recommend using this service. They have all account data that one 'generates' (its not actually generated but you just get pre-generated credentials) and they can possibly recover those accounts. 
I would strongly advise making your own generator in c#. Biggest problem is captcha solving you could add either some kind of ocr or use human worker service. This might be useful reference: https://github.com/Ashesh3/Steam-Account-Generator

**Comment by BenCat07** [comment]
Hello, maintainer of accgen.cathook.club here. Yes we do store the data after usage, but that is mostly For recovering accounts for users, not to use your accounts for ourselves. It's your choice whether to believe us ( @a6d6061ed1 ). additionally steam got fed up with our generation and replaced their very easy captcha with a google captcha v2:

By the way the service you mentioned above is also by the same person who made accgen.cathook.club, i can have him respond here if you want. ( @Ashesh3 )

**Comment by Ashesh3** [comment]
> I wouldn't recommend using this service. They have all account data that one 'generates' (its not actually generated but you just get pre-generated credentials) and they can possibly recover those accounts.
> I would strongly advise making your own generator in c#. Biggest problem is captcha solving you could add either some kind of ocr or use human worker service. This might be useful reference: https://github.com/Ashesh3/Steam-Account-Generator

Hello, we do store accounts on the server, and to be honest we currently don't delete the account if you take it, but rest be assured your "temporary, throw and use, csgo account with no account value and no gametime, meant to be used to rage hack after a ban" account is safe. We don't access any accounts personally, and you are free to change the password for any account you obtain (add a phone number, reset email and pass using that). 

If you are generating accounts here to use it as your main account, stocking up games and adding hundreds of hours and spending a fortune in accounts generated from our website, this isn't for you then.
Our website started as a service to give away temporary throwaway accounts and not accounts on which you are gonna store your priceless skins.

Again we don't access any of your accounts, we don't track who, when took an account from our site.

Also: We're in process of moving the registration process client side, i.e the account will be made on your own browser and "no" data will ever be sent to our servers (all code will be made open source), we have submitted the necessary code for review and will release this new model as soon as it gets approved by the code review team.

Thanks for showing your concerns and i hope i addressed most if not all of them.

Ash
An Admin of accgen web
Owner of https://github.com/Ashesh3/Steam-Account-Generator

**Comment by a6d6061ed1** [comment]
> > I wouldn't recommend using this service. They have all account data that one 'generates' (its not actually generated but you just get pre-generated credentials) and they can possibly recover those accounts.
> > I would strongly advise making your own generator in c#. Biggest problem is captcha solving you could add either some kind of ocr or use human worker service. This might be useful reference: https://github.com/Ashesh3/Steam-Account-Generator
> 
> Hello, we do store accounts on the server, and to be honest we currently don't delete the account if you take it, but rest be assured your "temporary, throw and use, csgo account with no account value and no gametime, meant to be used to rage hack after a ban" account is safe. We don't access any accounts personally, and you are free to change the password for any account you obtain (add a phone number, reset email and pass using that).
> 
> If you are generating accounts here to use it as your main account, stocking up games and adding hundreds of hours and spending a fortune in accounts generated from our website, this isn't for you then.
> Our website started as a service to give away temporary throwaway accounts and not accounts on which you are gonna store your priceless skins.
> 
> Again we don't access any of your accounts, we don't track who, when took an account from our site.
> 
> Also: We're in process of moving the registration process client side, i.e the account will be made on your own browser and "no" data will ever be sent to our servers (all code will be made open source), we have submitted the necessary code for review and will release this new model as soon as it gets approved by the code review team.
> 
> Thanks for showing your concerns and i hope i addressed most if not all of them.
> 
> Ash
> An Admin of accgen web
> Owner of https://github.com/Ashesh3/Steam-Account-Generator

I appreciate your response although I still think there's no need to use third party online service for something that can be done entirely in C#. I assume your service has high uptime but it still might go down someday and then account generator embedded in SAM will stop working. As much as I'd like to belive your claims, there's no way this can be verified.

By the way that client side account creator you mentioned really got my attention. Im especially curious about solving recaptcha v2, will you use voice recognition (to break recaptcha audio challenge) of some kind? Also it's a nice touch to open source your service, keep it up.

**Comment by Ashesh3** [comment]
> > > I wouldn't recommend using this service. They have all account data that one 'generates' (its not actually generated but you just get pre-generated credentials) and they can possibly recover those accounts.
> > > I would strongly advise making your own generator in c#. Biggest problem is captcha solving you could add either some kind of ocr or use human worker service. This might be useful reference: https://github.com/Ashesh3/Steam-Account-Generator
> > 
> > 
> > Hello, we do store accounts on the server, and to be honest we currently don't delete the account if you take it, but rest be assured your "temporary, throw and use, csgo account with no account value and no gametime, meant to be used to rage hack after a ban" account is safe. We don't access any accounts personally, and you are free to change the password for any account you obtain (add a phone number, reset email and pass using that).
> > If you are generating accounts here to use it as your main account, stocking up games and adding hundreds of hours and spending a fortune in accounts generated from our website, this isn't for you then.
> > Our website started as a service to give away temporary throwaway accounts and not accounts on which you are gonna store your priceless skins.
> > Again we don't access any of your accounts, we don't track who, when took an account from our site.
> > Also: We're in process of moving the registration process client side, i.e the account will be made on your own browser and "no" data will ever be sent to our servers (all code will be made open source), we have submitted the necessary code for review and will release this new model as soon as it gets approved by the code review team.
> > Thanks for showing your concerns and i hope i addressed most if not all of them.
> > Ash
> > An Admin of accgen web
> > Owner of https://github.com/Ashesh3/Steam-Account-Generator
> 
> I appreciate your response although I still think there's no need to use third party online service for something that can be done entirely in C#. I assume your service has high uptime but it still might go down someday and then account generator embedded in SAM will stop working. As much as I'd like to belive your claims, there's no way this can be verified.
> 
> By the way that client side account creator you mentioned really got my attention. Im especially curious about solving recaptcha v2, will you use voice recognition (to break recaptcha audio challenge) of some kind? Also it's a nice touch to open source your service, keep it up.

> I still think there's no need to use third party online service for something that can be done entirely in C#.
Yep, the only reason why someone would use the online service is,
1. Convenience,  can be loaded up instantly, makes accounts in a second (c# will takes ~20-30 secs) , this is because our accounts are pre generated hence using the online service makes it instant and convenient to get account.  
2. Since the Web gen is.. well.. on the web, it can be used on any device which supports a web browser.. on your phones too where c# software would fail
3. When you have no clue how to and / or don't want to code a c# software that'll take hours of your work just to make a steam account..
4. Keeping it maintained, we change email domain every 5-6 days, sometimes twice a day, steam is catching up quick to ban temp email services, we use our own email servers to change , handle mail processing, if you decide to use c# you'll need a vps with postfix or any similar service, i can confirm 99.99% of all online based temp emails are banned, also just changing domain won't help, they ban the mx server's IP.. so you might need to get a vps which has a dynamic IP. 
5. Since we have recaptcha v2 now... yep unfortunately now if you go by c# you'll need to use a browser emulation bundle, that increases the file size to + 100mb at least if not more. also the browser emulator is gonna get very bad recaptcha challenges.. of course google detects it!


> I assume your service has high uptime but it still might go down someday and then account generator embedded in SAM will stop working

we try our best to have maximum uptime, we have recorded no unintentional downtimes since March 1st ,2019
when steam introduced recaptchas, we had a downtime of 30 mins, for reasons obvious.
In such a drastic change to steam's reg process, updating a c# gen could take hours and hours of testing, (also need to embed a browser emulator now)

>As much as I'd like to belive your claims, there's no way this can be verified.
That's right, same goes for most online services, there's no way to verify the claims. Some people don't mind us (accgen.cathook.com)  to having stored the accounts which we made ourselves.. (pre storage concept).. all they wanna use is rage and throw, i agree concerns might arise when you're thinking to spend a fortune on an account generated on our website, in that case, please make a steam account normally.

>By the way that client side account creator you mentioned really got my attention.
We're ready for release, our addons have been approved by both Chrome and Firefox stores (Addon is open sourced), expect an announcement soon!

>Im especially curious about solving recaptcha v2, will you use voice recognition (to break recaptcha audio challenge) of some kind?

Unfortunately, they user will need to solve the recaptcha themselves, we just automate everything else except the solving part.

Thanks for your concerns.

**Comment by a6d6061ed1** [comment]
since this is still open I'd like to point out that incident with cathook account generator occured and a lot of accounts generated via their site were suspended by valve and it wasnt possible to login to them. naturally that's a risk that comes with using public account generator such as this one
