### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sp0ok3r** [rex706/SAM#4]
1 º -  If description is blank, don't display it on menu,

2 º - Maybe add minimize,

3 º - Add setting to auto save steam (remember password)
Because when my windows starts, i have to type the pw in. (2lazy4SteamGuard)
![forsam](https://cloud.githubusercontent.com/assets/7952298/22528829/dec8859e-e8cc-11e6-8645-9bf689ada560.jpg)

**Comment by rex706** [comment]
The blank description was an easy fix. I had no idea that was an issue since I use descriptions for all of my accounts. Minimize I have been on the fence about, but since you suggested I will enable it.

As for the 'Remember my password' setting, though, that may not be possible. Currently, I am using Steam's command line parameters to log in the selected account. There is no parameter for enabling that check box. Even forcing the check box to enable in memory while this window is open doesn't seem to do the trick as exiting Steam and re-opening it will still prompt for account information. But I'll keep trying!

**Comment by sp0ok3r** [comment]
Thanks!
