### ISSUE TITLE
Password not supporting some special characters.

### ISSUE THREAD

**Issue by 0450** [rex706/SAM#41]
Most of my passwords with special characters always fails when trying to log in with SAM but its fine when i enter it manually. The passwords consists of !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

**Comment by rex706** [comment]
@0450 It is most likely the '-' character that causes the problem. Since SAM uses the  [built in Steam login parameters](https://support.steampowered.com/kb_article.php?ref=5623-QOSV-5250) to do the initial logging in, it probably interprets everything after that character as a launch parameter. Now that I have some more free time I am looking further into #35, which likely relates to this issue as well.

**Comment by rex706** [comment]
Reopened this issue as some special characters like the hyphen `-` will not be usable in passwords currently with the `-login` parameter enabled.

**Comment by rex706** [comment]
Update: Looks like [this](https://stackoverflow.com/questions/10296162/escaping-special-characters-in-cmd) works in the limited tests I have run so far. Appending quotes around the password still logs in successfully through the -login argument. I may need to handle a few special cases with certain characters like quotes and percents as mentioned in the link but that shouldn't be too bad.

**Comment by rex706** [comment]
Update 2: As far as I can tell, after surrounding the password with quotes `"` and escaping quotes in the password with a backslash '\' instead of additional quotes as the linked article in my previous update suggested, all other special characters seem to work fine using !"#$%&'()*+,-./:;<=>?@[]^_`{|}~ as a test password on a random test account. 

Should hopefully be able to release a new version with this fixed some time this week!
