### ISSUE TITLE
Dsable auto-update

### ISSUE THREAD

**Issue by LL1r1k** [rex706/SAM#53]
How I can disable auto-update when the program is loading.

**Comment by rex706** [comment]
@LL1r1k Is there a specific reason you don't want to use the latest version?

**Comment by LL1r1k** [comment]
I have a problem with the latest update. Steam don't enter after its opening. Like in #47 issue.

**Comment by rex706** [comment]
@LL1r1k are you using the -login parameter setting and running SAM as admin?

**Comment by LL1r1k** [comment]
Yes. I tried to run as admini, the same

**Comment by rex706** [comment]
@LL1r1k is the '-login' parameter setting enabled under Parameters?

**Comment by LL1r1k** [comment]
Yest the -login parameter setting enabled. But on old version all file.

**Comment by LL1r1k** [comment]
The main question, can i disable auto update?

**Comment by rex706** [comment]
@LL1r1k  Not natively in the application no. I will add it as a setting in the latest version, but that won't solve your problem as you will have to be on the latest version to disable it. You *could* try making a firewall rule or edit to your hosts file to prevent calls to https://raw.githubusercontent.com/rex706/SAM/master/latest.txt and https://textuploader.com/58mva/raw since you prefer to use an older version if it bothers you that much. 

Is there any more information you can give me about the problem? I don't have any issue at all with what you're describing and if I can't reproduce the issue myself it is very difficult to troubleshoot and then fix. Which part fails? The initial Steam login window? Typing the 2FA code? Does it type anything at all or something incorrect? A video or picture of some kind may help out a lot here.

**Comment by rex706** [comment]
@LL1r1k another user had a similar issue and I found it was caused by the Steam Login window not being detected properly in other languages. Do you run Steam in a language other than English? The new version should resolve your issue in this case.
