### ISSUE TITLE
Username field won't accept e-mail

### ISSUE THREAD

**Issue by Baxxster** [rex706/SAM#6]
Hello,

There's a problem adding an steam account that was created a long, long time ago that requires login with e-mail and not username. Is it possible to get support for e-mails in "Username" field?

**Comment by rex706** [comment]
Does steam allow logins with email instead of username still? I just tried it a few times with no success. Could just be an account setting of mine somewhere though. 

I fixed the error that caused emails not being accepted in the username field and will push an update if you are sure emails can be used at the steam login window.

**Comment by Baxxster** [comment]
Yes, they do still support e-mail login, and Unable to convert the account to a "normal username" :( Would be great if you add this support! :)

**Comment by rex706** [comment]
Pushed the fix! Let me know if there is any issues.

**Comment by dico** [comment]
Thank you! This fix helped me use my first steam account, which still uses mail login.
