### ISSUE TITLE
Unable to check 'remember me'

### ISSUE THREAD

**Issue by Suphax** [rex706/SAM#64]
I'm not sure if this is because I am using a [skin](https://metroforsteam.com/), but SAM doesn't check 'remember me' even if the setting is turned on.

![Settings Page](https://i.suphax.dev/Fuw2c.png)

Let me know if I can give any more info.

**Comment by Suphax** [comment]
Nevermind I thought I checked all the closed/open issues but just saw #63.

**Comment by rex706** [comment]
@Suphax there is actually an issue with using the `Remember Me` functionality while also using the `-login` parameter #35. Steam does not let you check the box or use the reg key entry to force it on. I've even found and forced the bit that controls the checkbox in memory for the Steam login window to be checked with no effect. The downside of not using the '-login' parameter is that SAM will then type your credentials in the input boxes itself. There is a bug that I have fixed and will likely release a hotfix for today that will address #61 and correctly focus the Steam login window before every key press since there doesn't seem to be reliable way to send key presses to Steam without it being in focus.
