### ISSUE TITLE
avast sandbox

### ISSUE THREAD

**Issue by alprutxd** [rex706/SAM#75]
Can I open steam in sandbox with this (I use avast)

**Comment by rex706** [comment]
What happens if you try?

**Comment by alprutxd** [comment]
It just freezes (Also running steam in windows 7) 
![billede](https://user-images.githubusercontent.com/42916890/69938715-4750e300-14de-11ea-93a7-16ffd9526c62.png)

**Comment by rex706** [comment]
What freezes? The whole application? Entering the Steam Guard code? The more information you can provide me the better.

Also, since you are running in a VM, you may be experiencing a similar issue to #67.

You could try installing the latest [.NET framework](https://dotnet.microsoft.com/download) and see if that helps.

**Comment by alprutxd** [comment]
he whole application, my steam does not even open, and non of the accounts i am using is using steam guard, so I dont have to enter any form of code.

when steam is closed i can open one, but the next one I open needs username and password

**Comment by alprutxd** [comment]
And the whole application freezes, when I open my second steam window

**Comment by rex706** [comment]
After digging a little through the Avast Sandbox documentation as I have no plans to actually download Avast, it appears that ["a list of common system locations is Blocked by default"](https://help.avast.com/en/av_free/17/settings_sandbox_params.html) for programs running in the Sandbox under the **Privacy** section. In order for SAM to _open_ Steam, it needs access to the location where Steam is installed. Since this is usually in the `Program Files (x86)` directory by default, I imagine Avast Sandbox is blocking SAM from going to your Steam directory to do its job. The documentation claims the user (you) can add application specific exclusions for specific locations (also under the **Privacy** section), which is what I would recommend you trying for SAM and your Steam directory.

**Comment by alprutxd** [comment]
SAM still seems to freeze after i have added it to allowed, I can fine open one steam window, but when I try to open the secondSAM freezes and steam needs Username and password

**Comment by alprutxd** [comment]
I can also only add .exe filles, cant add a locations

**Comment by alprutxd** [comment]
And I don't run SAM in sandbox, I run SAM normal

**Comment by rex706** [comment]
Can you explain to me what you are trying to accomplish exactly? From what I understand, SAM works fine for the first account, but freezes the second time? Or are you trying to open multiple instances of the Steam client? If you're not running SAM in Sandbox, then what are you using Sandbox for?

**Comment by alprutxd** [comment]
I'm trying to to run more steam instances

**Comment by rex706** [comment]
Ok I think I understand. You are using Avast Sandbox to open Steam so you can have multiple client instances open at once since Steam does not support this capability natively. 

In this case SAM may be hanging while waiting for the previous Steam process to exit because of Sandbox, since part of SAM's logic is to send the -shutdown parameter to the existing open Steam process (if one is found) to logout the previously logged in user. 

I will see what I can do about this very unique scenario, but currently both Steam and SAM are not designed to handle multiple instances of the Steam client itself.

**Comment by alprutxd** [comment]
Okay thanks, I can easly open more steam instances without SAM, but I dont want to type every username and password myself, so it's SAM thats doing something :D But I hope you can help me :)

**Comment by alprutxd** [comment]
And yeah its properly that -shutdown, because when I close the steam in sandbox, it opens the next account with no proplem

**Comment by rex706** [comment]
[SAM_1.4.1.0-Pre1.zip](https://github.com/rex706/SAM/files/3918554/SAM_1.4.1.0-Pre1.zip)

Please try this pre-release version, enable 'Sandbox Mode' in the settings, and let me know if it solves your issue. If so, I will prepare a new release.

**Comment by alprutxd** [comment]
Works bro :D ty <3
