### ISSUE TITLE
Password bug still exists

### ISSUE THREAD

**Issue by Acecool** [rex706/SAM#77]
I tried SAM for the first time today, and when it asked me if I wanted to 'secure' SAM with a password, I chose yes. As is customary for new apps, I first use a throw-away password... Lets call it '123'.

I entered 123 as my password, and I clicked ok. SAM launched after I entered it a second time. I then went through the settings and adjusted them.

Afterwards, it asked me for my password. I entered 123, and it said 'invalid password'. I tried any possible variant / typo variant I could think of, but it wasn't possible to have screwed up '123' because of the location of the keys, etc..

I then edited the settings file and set 
```
PasswordProtect=False
```

and SAM launched just fine.... Is this really all the protection there is?

Second - no matter how many times I try canceling, or entering without a password - SAM will NOT close which is incredibly annoying. I had to close it via the Task Manager, or edit the config file to 'remove the protection' and then hit cancel before SAM would launch again. This password window comes up in settings, it comes up when launching, if I try to enable password in settings...

It doesn't let me edit the password so I'll probably have to review the code to see where it even stores it which takes time.

I will do some tests with a throwaway account to see if SAM does actually have 'protection' or not. Also, why is there no 'uninstall'? If I run it for the first time in a new folder, it doesn't ask for a new password so it is likely stored in the registry, or somewhere else... But, being unable to reset is a problem too.

Also, info.dat is basically empty. Only a header exists.

**Comment by rex706** [comment]
This appears to be a bug when using SAM _without_ any accounts added to the application. 

The PasswordProtect boolean value is only an initial check to let the program easily know password protection is enabled. When enabled, the entire info.dat file is encrypted when accounts are serialized and saved using the password provided. If you were to go into the SAMSettings.ini and change PasswordProtect to false, the application will crash attempting to deserialize the encrypted info.dat file without a password. 

In the event that _no accounts_ are added to the application, there is no data to encrypt and save to info.dat, which is where this problem arises. 

There are no keys stored in the registry as this would cause issues for users without that level of system access. This is a portable application, which is why there is no "uninstall", and if you delete the SAMSettings.ini file and restart the application, you will be once again prompted for a password as if it were the first use.

The actual password provided by the user to be used by the whole application is not stored anywhere. It will either successfully decrypt info.dat or fail and re-prompt for the correct password.

There is definitely some logic that needs reworking in regards to the prompts continuing to appear when they probably shouldn't, which I will look into, but basically if you add any account (even some dummy data) to the application your problems will likely go away. 

Have you tried to use the program with an account added?

**Comment by rex706** [comment]
Please try the [latest release](https://github.com/rex706/SAM/releases) (or run SAM and it should prompt you to let it update itself) and let me know if you still experience issues.

**Comment by Acecool** [comment]
Appears to be resolved... I am going to post a new bug report though... The settings file isn't read for the initial enter your password dialog. ie: I set the skin to default light, blue highlights. It is dark when that shows up.

Password dialog works, gives error when wrong, etc..

Info.dat looks correct.
