### ISSUE TITLE
SAM just closes

### ISSUE THREAD

**Issue by ColinTheShark** [rex706/SAM#78]
I have no second instance of SAM running and when I open it, it appears for a moment and just disappears again. It's available from the icon tray next to the system clock, but hovering over the icon just makes it disappear (indicating a crashed process maybe?). I don't know what might help, so here's a gif of what happens (roughly).

![](https://i.imgur.com/kFvzfd6.gif)

<sub>My taskbar is at the bottom normally, I moved it up for demonstration purposes lol</sub>

**Comment by ColinTheShark** [comment]
Okay, seems like a recent update broke things.

I did not enable encryption of the data because I don't need it (reliably the only user). Turns out, an update has encrypted the data and I never specified a password (since I never encrypted it).

Backup file (as seen in the GIF of my initial comment) and the new one SAM generated.

![Backup](https://i.imgur.com/7voFUEC.png)
![New File](https://i.imgur.com/q1ENc1y.png)

Since I got a backup (not *that* recent, but it's something), I'm not hit that much, but I can imagine others having lost all data due to this.

**Comment by rex706** [comment]
Is it possible that you may have made a manual edit that could have corrupted the dat file? After looking at the logic for determining whether password protection is enabled, it will first look at the user password protection settings and if that is false it will attempt to deserialize the file _without_ a password, and if that fails it will return password protected is true.

However, you should be able to recover your dat file by setting password protection to true in your settings file manually and leaving the password field blank when prompted. Then disable password protection through the application to decrypt it (again just leaving the password prompt blank).

I will look into forcing the user to not have an empty password instead of prompting if the user is sure and then also check against the password length to be greater than 0 before returning true for the password protection check.

**Comment by ColinTheShark** [comment]
I have always verified to only make legit changes and keep the XML Layout 1:1 in all cases. That's why I was surprised to find it this way. I also have never set a password, which further confused me as to why it was suddenly encrypted.

---
> you should be able to recover your dat file

I was, I kept a backup after deleting some accounts a few weeks ago :P

**Comment by ColinTheShark** [comment]
I don't know how, but it randomly encrypted the `info.dat` again. No password was set, SAM just closes right after opening.

**Comment by rex706** [comment]
Are you making manual edits to `info.dat`? Are you using any strange characters for any inputs? While the next release should solve this issue by checking password length (since it can never be 0 after the initial password prompt), the only event that would cause this in the first place is a problem deserializing the file itself _without_ a password.

**Comment by ColinTheShark** [comment]
I sometimes edit the info.dat manually when I have to put in a lot of info at the same time (e.g. profile URLs for 10+ accounts).

But: I always make sure to adhere to the previous standard and layout and also check if anything breaks.

**Comment by Nou4r** [comment]
How can we solve this? I dont have a backup for my config file

**Comment by Nou4r** [comment]
WTF it keeps encrypting itself out of fucking nowhere this is the second time i lost a batch of accounts and there isnt even a solution to this??

**Comment by rex706** [comment]
@Nou4r are you making manual edits to your info.dat file? You can try the temporary fix I suggested earlier in this thread.

**Comment by Nou4r** [comment]
I do not touch my info.dat file whatsoever and sadly that temp fix didn't work out for me.

**Comment by rex706** [comment]
@Nou4r  As mentioned higher up in the thread, the reason this is a problem in the first place is because your info.dat **fails to deserialize**. I have already comitted code to fix the issue of encrypting the file when this happens, but without knowing why it occurs for you in the first place it will still render your file unusable. Do you use any less than or greater than characters (< >)? If not, you may have to provide me your files (omitting important info of course) so I can test locally. There is simply no other way for me to know as I have never experienced this issue before personally.
