### ISSUE TITLE
No arguments found

### ISSUE THREAD

**Issue by Asmund11** [rex706/SAM#79]
https://i.imgur.com/uGRVNP5.png

It happens when i try to update SAM using Updater. If i try to update SAM through SAM.exe then everything is good

**Comment by Asmund11** [comment]
Btw SAM closes when i try to open Settings

**Comment by rex706** [comment]
You have asked about this before and I've mentioned that [the updater is not supposed to be run independently](https://github.com/rex706/SAM/issues/25#issuecomment-475813137). I will look into downloading the updater when updating and then deleting it afterwards when it is no longer needed  since it is a small file so users won't try to use it out of context.

Also, SAM does not close when opening Settings for me. Could you please update your SAMSettings.ini file?

**Comment by Asmund11** [comment]
Check this out
https://streamable.com/fx33b
[Новый текстовый документ.txt](https://github.com/rex706/SAM/files/3947527/default.txt)
