### ISSUE TITLE
Updater.exe keeps deleting itself and won't update

### ISSUE THREAD

**Issue by KillaBoi** [rex706/SAM#94]
I have 1.4.1.0 and I'm trying to update it to 1.4.1.1, it says it's reading the update manifest file but then just closes itself.

Any ideas?

**Comment by rex706** [comment]
Some users were trying to run the updater independently without passing it any arguments, which the updater requires, so to avoid confusion SAM will delete the updater when it is not needed and acquire it only when updating. This shouldn't really be a big issue since the updater is such a small file. 

I'm not sure what is going on with the inability to read the manifest, as it is just a link to: 
https://github.com/rex706/SAM/blob/master/latest.txt

The updater doesn't run any differently than before except for it now wants to run as administrator as this is required if you place your SAM files somewhere in one of your Program Files folders. I'll take a look to see if I can reproduce the problem in another environment.

**Comment by 2Eggsss** [comment]
I just downloaded the latest SAM.exe and moved it into my current folder and deleted the old one and that seemed to do the trick, but worth looking into...
Cheers!

**Comment by KillaBoi** [comment]
I'm self closing this since it seems to have been fixed...
