### ISSUE TITLE
Bans aren't being displayed

### ISSUE THREAD

**Issue by PeniPeg** [rex706/SAM#96]
the title says it...

I am using my api key but nothing happens upon reloading or refreshing the accounts

**Comment by rex706** [comment]
The application will store each account's unique steam id in the info.dat file if it can be found from either your config.vdf file in your `\Steam\config` file path, or from the profile (vanity) url if you provided one when adding the account to SAM. The steam id is needed in order to utilize the web api to collect information about accounts like their bans. In order for an account to exist in your config.vdf file, it has to have logged in at least once on that machine. If you are still having issues, your config.vdf may be old and have a lowercase "steam" instead of an uppercase "Steam". If this is the case I can either make SAM correct this or look through the lowercase path as well. 

![image](https://user-images.githubusercontent.com/15636269/77557592-4fb79a00-6e90-11ea-88ed-26621f2b4fa4.png)

Let me know.

**Comment by PeniPeg** [comment]
completely removed SAM with exports and reinstalled it, works now :)

**Comment by wrLd1337** [comment]
> If this is the case I can either make SAM correct this or look through the lowercase path as well.
> 

Please add that!

Thanks!
